#!/usr/bin/env python3
"""
Reads the summary file generated by the binning chain script, and finds the best bin per taxonomy
Copies these bins over to a new directory

Usage:
(python) Pipeline_bin_copier summary_file /old_dir/with/bins /new_dir/with/best_bins
"""
###################
#Import statements
###################  

import sys
import os
import shutil

###################
#File handling functions
###################  
def gen_line_reader(file_path):
    for line in open(file_path, "r"):
        yield line

summary_file = sys.argv[1]
old_dir = sys.argv[2]
new_dir = sys.argv[3]

copy_list = []
tax = ""
for line in gen_line_reader(summary_file):
    if line.startswith("d__"):
        tax = line.strip()
    elif line.startswith("MAG\tCompletion"):
        continue
    elif tax.strip():
        mag = line.partition("\t")[0].strip() + ".fa"
        copy_list.append(mag)
        tax = ""

if not os.path.isdir(new_dir):
    os.mkdir(new_dir)

for file in copy_list:
    try:
        shutil.copyfile(os.path.join(old_dir, file), os.path.join(new_dir, file))
    except:
        print("Could not copy {}. Perhaps the extension is not correct".format(os.path.join(old_dir, file)))

        
    